"""
Standardization layer.
Turns an ExtractedTable into:
  - a clean Markdown table string
  - (optionally) a natural-language summary of it, generated by an LLM

Design choice: we embed the SUMMARY (high semantic signal) and store the
MARKDOWN as retrievable payload/metadata. Raw table cells embed poorly on
their own, so this split noticeably improves retrieval quality.
"""
import os
import requests
from tenacity import retry, stop_after_attempt, wait_exponential
from app.extract import ExtractedTable

# Point this at whatever OpenAI-compatible chat endpoint you have access to.
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://api.openai.com/v1")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4o-mini")


def _forward_fill_headers(headers: list) -> list:
    """Fill blank/merged-cell header slots with the last seen non-empty value."""
    filled, last = [], ""
    for h in headers:
        h = (h or "").strip()
        if h:
            last = h
        filled.append(last if not h else h)
    return filled


def to_markdown(table: ExtractedTable) -> str:
    headers = _forward_fill_headers(table.headers)
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in table.rows:
        # pad/truncate ragged rows so the markdown stays well-formed
        cells = list(row) + [""] * (len(headers) - len(row))
        cells = cells[: len(headers)]
        lines.append("| " + " | ".join(str(c) for c in cells) + " |")
    return "\n".join(lines)


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=8))
def summarize_table(markdown: str, context_hint: str = "") -> str:
    """
    Calls a chat completion endpoint to produce a 2-4 sentence natural-language
    summary of the table, used as the embedded text.
    """
    if not LLM_API_KEY:
        # Offline fallback so the pipeline still runs without an API key configured.
        first_line = markdown.splitlines()[0]
        return f"Table with columns: {first_line.strip('| ').replace('|', ',')}."

    resp = requests.post(
        f"{LLM_BASE_URL}/chat/completions",
        headers={"Authorization": f"Bearer {LLM_API_KEY}"},
        json={
            "model": LLM_MODEL,
            "messages": [
                {
                    "role": "system",
                    "content": "Summarize the following Markdown table in 2-4 "
                    "sentences: what it covers, key columns, and any notable "
                    "figures. Be concise and factual.",
                },
                {"role": "user", "content": f"{context_hint}\n\n{markdown}"},
            ],
            "temperature": 0.2,
        },
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def standardize(table: ExtractedTable) -> dict:
    md = to_markdown(table)
    summary = summarize_table(md, context_hint=f"Source: {table.source_file} ({table.location})")
    return {
        "markdown": md,
        "summary": summary,
        "source_file": table.source_file,
        "location": table.location,
    }
